admin:
    resource: "@MaillingListBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin/
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin/

mailing_list:
    resource: "@MaillingListBundle/Controller/MailingList"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    