mailing_list:
    resource: "@MaillingListBundle/Controller/MailingList"
    type:     annotation
    prefix:   /

admin:
    resource: "@MaillingListBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin/
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    